# Form implementation generated from reading ui file '/home/park/dev_ws/iot-repo-3/src/GUI_v2/demo/test.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


